version: 3
workdir: internal
allow:
  depOnAnyVendor: true

components:
  adapter: { in: adapter/** }
  application: { in: application/** }
  di: { in: di/** }
  core: { in: core/application/** }
  domain: { in: core/domain/** }
  presenter: { in: presenter/** }
  pkg: { in: ../pkg/** }

deps:
  di:
    mayDependOn:
      - adapter
      - application
      - core
      - di
      - presenter
      - domain
      - pkg
  application:
    mayDependOn:
      - adapter
      - application
      - core
      - di
      - presenter
      - domain
      - pkg
  presenter:
    mayDependOn:
      - core
      - presenter
      - domain
      - pkg
  core:
    mayDependOn:
      - adapter
      - core
      - domain
      - pkg
  adapter:
    mayDependOn:
      - domain
      - pkg
  domain:
    mayDependOn:
      - domain
      # TODO: split errs to domain, networks
      - pkg
