// Code generated by "enumer -type ReportType -text -transform=lower"; DO NOT EDIT.

package report

import (
	"fmt"
	"strings"
)

const _ReportTypeName = "autocheckcustomgitlabjsonmarkdownnistoud4owaspowaspmpcidssplainreportsanssarifxml"

var _ReportTypeIndex = [...]uint8{0, 9, 15, 21, 25, 33, 37, 41, 46, 52, 58, 69, 73, 78, 81}

const _ReportTypeLowerName = "autocheckcustomgitlabjsonmarkdownnistoud4owaspowaspmpcidssplainreportsanssarifxml"

func (i ReportType) String() string {
	if i >= ReportType(len(_ReportTypeIndex)-1) {
		return fmt.Sprintf("ReportType(%d)", i)
	}
	return _ReportTypeName[_ReportTypeIndex[i]:_ReportTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ReportTypeNoOp() {
	var x [1]struct{}
	_ = x[AutoCheck-(0)]
	_ = x[Custom-(1)]
	_ = x[Gitlab-(2)]
	_ = x[Json-(3)]
	_ = x[Markdown-(4)]
	_ = x[Nist-(5)]
	_ = x[Oud4-(6)]
	_ = x[Owasp-(7)]
	_ = x[Owaspm-(8)]
	_ = x[Pcidss-(9)]
	_ = x[PlainReport-(10)]
	_ = x[Sans-(11)]
	_ = x[Sarif-(12)]
	_ = x[Xml-(13)]
}

var _ReportTypeValues = []ReportType{AutoCheck, Custom, Gitlab, Json, Markdown, Nist, Oud4, Owasp, Owaspm, Pcidss, PlainReport, Sans, Sarif, Xml}

var _ReportTypeNameToValueMap = map[string]ReportType{
	_ReportTypeName[0:9]:        AutoCheck,
	_ReportTypeLowerName[0:9]:   AutoCheck,
	_ReportTypeName[9:15]:       Custom,
	_ReportTypeLowerName[9:15]:  Custom,
	_ReportTypeName[15:21]:      Gitlab,
	_ReportTypeLowerName[15:21]: Gitlab,
	_ReportTypeName[21:25]:      Json,
	_ReportTypeLowerName[21:25]: Json,
	_ReportTypeName[25:33]:      Markdown,
	_ReportTypeLowerName[25:33]: Markdown,
	_ReportTypeName[33:37]:      Nist,
	_ReportTypeLowerName[33:37]: Nist,
	_ReportTypeName[37:41]:      Oud4,
	_ReportTypeLowerName[37:41]: Oud4,
	_ReportTypeName[41:46]:      Owasp,
	_ReportTypeLowerName[41:46]: Owasp,
	_ReportTypeName[46:52]:      Owaspm,
	_ReportTypeLowerName[46:52]: Owaspm,
	_ReportTypeName[52:58]:      Pcidss,
	_ReportTypeLowerName[52:58]: Pcidss,
	_ReportTypeName[58:69]:      PlainReport,
	_ReportTypeLowerName[58:69]: PlainReport,
	_ReportTypeName[69:73]:      Sans,
	_ReportTypeLowerName[69:73]: Sans,
	_ReportTypeName[73:78]:      Sarif,
	_ReportTypeLowerName[73:78]: Sarif,
	_ReportTypeName[78:81]:      Xml,
	_ReportTypeLowerName[78:81]: Xml,
}

var _ReportTypeNames = []string{
	_ReportTypeName[0:9],
	_ReportTypeName[9:15],
	_ReportTypeName[15:21],
	_ReportTypeName[21:25],
	_ReportTypeName[25:33],
	_ReportTypeName[33:37],
	_ReportTypeName[37:41],
	_ReportTypeName[41:46],
	_ReportTypeName[46:52],
	_ReportTypeName[52:58],
	_ReportTypeName[58:69],
	_ReportTypeName[69:73],
	_ReportTypeName[73:78],
	_ReportTypeName[78:81],
}

// ReportTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ReportTypeString(s string) (ReportType, error) {
	if val, ok := _ReportTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ReportTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ReportType values", s)
}

// ReportTypeValues returns all values of the enum
func ReportTypeValues() []ReportType {
	return _ReportTypeValues
}

// ReportTypeStrings returns a slice of all String values of the enum
func ReportTypeStrings() []string {
	strs := make([]string, len(_ReportTypeNames))
	copy(strs, _ReportTypeNames)
	return strs
}

// IsAReportType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ReportType) IsAReportType() bool {
	for _, v := range _ReportTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for ReportType
func (i ReportType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ReportType
func (i *ReportType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ReportTypeString(string(text))
	return err
}
