// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queue

import (
	"context"

	"github.com/POSIdev-community/aictl/internal/core/domain/queue"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAI creates a new instance of MockAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAI {
	mock := &MockAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAI is an autogenerated mock type for the AI type
type MockAI struct {
	mock.Mock
}

type MockAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAI) EXPECT() *MockAI_Expecter {
	return &MockAI_Expecter{mock: &_m.Mock}
}

// GetScanQueue provides a mock function for the type MockAI
func (_mock *MockAI) GetScanQueue(ctx context.Context) ([]queue.Entry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetScanQueue")
	}

	var r0 []queue.Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]queue.Entry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []queue.Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queue.Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetScanQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScanQueue'
type MockAI_GetScanQueue_Call struct {
	*mock.Call
}

// GetScanQueue is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) GetScanQueue(ctx interface{}) *MockAI_GetScanQueue_Call {
	return &MockAI_GetScanQueue_Call{Call: _e.mock.On("GetScanQueue", ctx)}
}

func (_c *MockAI_GetScanQueue_Call) Run(run func(ctx context.Context)) *MockAI_GetScanQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_GetScanQueue_Call) Return(entrys []queue.Entry, err error) *MockAI_GetScanQueue_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockAI_GetScanQueue_Call) RunAndReturn(run func(ctx context.Context) ([]queue.Entry, error)) *MockAI_GetScanQueue_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeWithRetry provides a mock function for the type MockAI
func (_mock *MockAI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type MockAI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) InitializeWithRetry(ctx interface{}) *MockAI_InitializeWithRetry_Call {
	return &MockAI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *MockAI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *MockAI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) Return(err error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLI creates a new instance of MockCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLI {
	mock := &MockCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLI is an autogenerated mock type for the CLI type
type MockCLI struct {
	mock.Mock
}

type MockCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLI) EXPECT() *MockCLI_Expecter {
	return &MockCLI_Expecter{mock: &_m.Mock}
}

// ShowQueue provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowQueue(ctx context.Context, entries []queue.Entry) {
	_mock.Called(ctx, entries)
	return
}

// MockCLI_ShowQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowQueue'
type MockCLI_ShowQueue_Call struct {
	*mock.Call
}

// ShowQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - entries []queue.Entry
func (_e *MockCLI_Expecter) ShowQueue(ctx interface{}, entries interface{}) *MockCLI_ShowQueue_Call {
	return &MockCLI_ShowQueue_Call{Call: _e.mock.On("ShowQueue", ctx, entries)}
}

func (_c *MockCLI_ShowQueue_Call) Run(run func(ctx context.Context, entries []queue.Entry)) *MockCLI_ShowQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []queue.Entry
		if args[1] != nil {
			arg1 = args[1].([]queue.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_ShowQueue_Call) Return() *MockCLI_ShowQueue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowQueue_Call) RunAndReturn(run func(ctx context.Context, entries []queue.Entry)) *MockCLI_ShowQueue_Call {
	_c.Run(run)
	return _c
}
