// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reporttemplates

import (
	"context"

	"github.com/POSIdev-community/aictl/internal/core/domain/report"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAI creates a new instance of MockAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAI {
	mock := &MockAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAI is an autogenerated mock type for the AI type
type MockAI struct {
	mock.Mock
}

type MockAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAI) EXPECT() *MockAI_Expecter {
	return &MockAI_Expecter{mock: &_m.Mock}
}

// GetReportTemplates provides a mock function for the type MockAI
func (_mock *MockAI) GetReportTemplates(ctx context.Context, localization string) ([]report.Template, error) {
	ret := _mock.Called(ctx, localization)

	if len(ret) == 0 {
		panic("no return value specified for GetReportTemplates")
	}

	var r0 []report.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]report.Template, error)); ok {
		return returnFunc(ctx, localization)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []report.Template); ok {
		r0 = returnFunc(ctx, localization)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]report.Template)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, localization)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetReportTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReportTemplates'
type MockAI_GetReportTemplates_Call struct {
	*mock.Call
}

// GetReportTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - localization string
func (_e *MockAI_Expecter) GetReportTemplates(ctx interface{}, localization interface{}) *MockAI_GetReportTemplates_Call {
	return &MockAI_GetReportTemplates_Call{Call: _e.mock.On("GetReportTemplates", ctx, localization)}
}

func (_c *MockAI_GetReportTemplates_Call) Run(run func(ctx context.Context, localization string)) *MockAI_GetReportTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAI_GetReportTemplates_Call) Return(templates []report.Template, err error) *MockAI_GetReportTemplates_Call {
	_c.Call.Return(templates, err)
	return _c
}

func (_c *MockAI_GetReportTemplates_Call) RunAndReturn(run func(ctx context.Context, localization string) ([]report.Template, error)) *MockAI_GetReportTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeWithRetry provides a mock function for the type MockAI
func (_mock *MockAI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type MockAI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) InitializeWithRetry(ctx interface{}) *MockAI_InitializeWithRetry_Call {
	return &MockAI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *MockAI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *MockAI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) Return(err error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLI creates a new instance of MockCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLI {
	mock := &MockCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLI is an autogenerated mock type for the CLI type
type MockCLI struct {
	mock.Mock
}

type MockCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLI) EXPECT() *MockCLI_Expecter {
	return &MockCLI_Expecter{mock: &_m.Mock}
}

// ShowReportTemplates provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowReportTemplates(ctx context.Context, templates []report.Template) {
	_mock.Called(ctx, templates)
	return
}

// MockCLI_ShowReportTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowReportTemplates'
type MockCLI_ShowReportTemplates_Call struct {
	*mock.Call
}

// ShowReportTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - templates []report.Template
func (_e *MockCLI_Expecter) ShowReportTemplates(ctx interface{}, templates interface{}) *MockCLI_ShowReportTemplates_Call {
	return &MockCLI_ShowReportTemplates_Call{Call: _e.mock.On("ShowReportTemplates", ctx, templates)}
}

func (_c *MockCLI_ShowReportTemplates_Call) Run(run func(ctx context.Context, templates []report.Template)) *MockCLI_ShowReportTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []report.Template
		if args[1] != nil {
			arg1 = args[1].([]report.Template)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_ShowReportTemplates_Call) Return() *MockCLI_ShowReportTemplates_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowReportTemplates_Call) RunAndReturn(run func(ctx context.Context, templates []report.Template)) *MockCLI_ShowReportTemplates_Call {
	_c.Run(run)
	return _c
}

// ShowReportTemplatesQuiet provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowReportTemplatesQuiet(ctx context.Context, templates []report.Template) {
	_mock.Called(ctx, templates)
	return
}

// MockCLI_ShowReportTemplatesQuiet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowReportTemplatesQuiet'
type MockCLI_ShowReportTemplatesQuiet_Call struct {
	*mock.Call
}

// ShowReportTemplatesQuiet is a helper method to define mock.On call
//   - ctx context.Context
//   - templates []report.Template
func (_e *MockCLI_Expecter) ShowReportTemplatesQuiet(ctx interface{}, templates interface{}) *MockCLI_ShowReportTemplatesQuiet_Call {
	return &MockCLI_ShowReportTemplatesQuiet_Call{Call: _e.mock.On("ShowReportTemplatesQuiet", ctx, templates)}
}

func (_c *MockCLI_ShowReportTemplatesQuiet_Call) Run(run func(ctx context.Context, templates []report.Template)) *MockCLI_ShowReportTemplatesQuiet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []report.Template
		if args[1] != nil {
			arg1 = args[1].([]report.Template)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_ShowReportTemplatesQuiet_Call) Return() *MockCLI_ShowReportTemplatesQuiet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowReportTemplatesQuiet_Call) RunAndReturn(run func(ctx context.Context, templates []report.Template)) *MockCLI_ShowReportTemplatesQuiet_Call {
	_c.Run(run)
	return _c
}
