// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package scafeeds

import (
	"context"

	"github.com/POSIdev-community/aictl/internal/core/domain/scafeeds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAI creates a new instance of MockAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAI {
	mock := &MockAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAI is an autogenerated mock type for the AI type
type MockAI struct {
	mock.Mock
}

type MockAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAI) EXPECT() *MockAI_Expecter {
	return &MockAI_Expecter{mock: &_m.Mock}
}

// GetScaFeeds provides a mock function for the type MockAI
func (_mock *MockAI) GetScaFeeds(ctx context.Context, statuses []scafeeds.Status) ([]scafeeds.Package, error) {
	ret := _mock.Called(ctx, statuses)

	if len(ret) == 0 {
		panic("no return value specified for GetScaFeeds")
	}

	var r0 []scafeeds.Package
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []scafeeds.Status) ([]scafeeds.Package, error)); ok {
		return returnFunc(ctx, statuses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []scafeeds.Status) []scafeeds.Package); ok {
		r0 = returnFunc(ctx, statuses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scafeeds.Package)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []scafeeds.Status) error); ok {
		r1 = returnFunc(ctx, statuses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetScaFeeds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScaFeeds'
type MockAI_GetScaFeeds_Call struct {
	*mock.Call
}

// GetScaFeeds is a helper method to define mock.On call
//   - ctx context.Context
//   - statuses []scafeeds.Status
func (_e *MockAI_Expecter) GetScaFeeds(ctx interface{}, statuses interface{}) *MockAI_GetScaFeeds_Call {
	return &MockAI_GetScaFeeds_Call{Call: _e.mock.On("GetScaFeeds", ctx, statuses)}
}

func (_c *MockAI_GetScaFeeds_Call) Run(run func(ctx context.Context, statuses []scafeeds.Status)) *MockAI_GetScaFeeds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []scafeeds.Status
		if args[1] != nil {
			arg1 = args[1].([]scafeeds.Status)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAI_GetScaFeeds_Call) Return(packages []scafeeds.Package, err error) *MockAI_GetScaFeeds_Call {
	_c.Call.Return(packages, err)
	return _c
}

func (_c *MockAI_GetScaFeeds_Call) RunAndReturn(run func(ctx context.Context, statuses []scafeeds.Status) ([]scafeeds.Package, error)) *MockAI_GetScaFeeds_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeWithRetry provides a mock function for the type MockAI
func (_mock *MockAI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type MockAI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) InitializeWithRetry(ctx interface{}) *MockAI_InitializeWithRetry_Call {
	return &MockAI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *MockAI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *MockAI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) Return(err error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLI creates a new instance of MockCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLI {
	mock := &MockCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLI is an autogenerated mock type for the CLI type
type MockCLI struct {
	mock.Mock
}

type MockCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLI) EXPECT() *MockCLI_Expecter {
	return &MockCLI_Expecter{mock: &_m.Mock}
}

// ShowScaFeeds provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowScaFeeds(ctx context.Context, packages []scafeeds.Package) {
	_mock.Called(ctx, packages)
	return
}

// MockCLI_ShowScaFeeds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowScaFeeds'
type MockCLI_ShowScaFeeds_Call struct {
	*mock.Call
}

// ShowScaFeeds is a helper method to define mock.On call
//   - ctx context.Context
//   - packages []scafeeds.Package
func (_e *MockCLI_Expecter) ShowScaFeeds(ctx interface{}, packages interface{}) *MockCLI_ShowScaFeeds_Call {
	return &MockCLI_ShowScaFeeds_Call{Call: _e.mock.On("ShowScaFeeds", ctx, packages)}
}

func (_c *MockCLI_ShowScaFeeds_Call) Run(run func(ctx context.Context, packages []scafeeds.Package)) *MockCLI_ShowScaFeeds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []scafeeds.Package
		if args[1] != nil {
			arg1 = args[1].([]scafeeds.Package)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_ShowScaFeeds_Call) Return() *MockCLI_ShowScaFeeds_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowScaFeeds_Call) RunAndReturn(run func(ctx context.Context, packages []scafeeds.Package)) *MockCLI_ShowScaFeeds_Call {
	_c.Run(run)
	return _c
}
