// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package await

import (
	"context"

	"github.com/POSIdev-community/aictl/internal/core/domain/queue"
	"github.com/POSIdev-community/aictl/internal/core/domain/scanstage"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAI creates a new instance of MockAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAI {
	mock := &MockAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAI is an autogenerated mock type for the AI type
type MockAI struct {
	mock.Mock
}

type MockAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAI) EXPECT() *MockAI_Expecter {
	return &MockAI_Expecter{mock: &_m.Mock}
}

// GetScanItem provides a mock function for the type MockAI
func (_mock *MockAI) GetScanItem(ctx context.Context, id uuid.UUID) (queue.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetScanItem")
	}

	var r0 queue.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (queue.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) queue.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(queue.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetScanItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScanItem'
type MockAI_GetScanItem_Call struct {
	*mock.Call
}

// GetScanItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAI_Expecter) GetScanItem(ctx interface{}, id interface{}) *MockAI_GetScanItem_Call {
	return &MockAI_GetScanItem_Call{Call: _e.mock.On("GetScanItem", ctx, id)}
}

func (_c *MockAI_GetScanItem_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAI_GetScanItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAI_GetScanItem_Call) Return(item queue.Item, err error) *MockAI_GetScanItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockAI_GetScanItem_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (queue.Item, error)) *MockAI_GetScanItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetScanStage provides a mock function for the type MockAI
func (_mock *MockAI) GetScanStage(ctx context.Context, projectId uuid.UUID, scanId uuid.UUID) (scanstage.ScanStage, error) {
	ret := _mock.Called(ctx, projectId, scanId)

	if len(ret) == 0 {
		panic("no return value specified for GetScanStage")
	}

	var r0 scanstage.ScanStage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (scanstage.ScanStage, error)); ok {
		return returnFunc(ctx, projectId, scanId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) scanstage.ScanStage); ok {
		r0 = returnFunc(ctx, projectId, scanId)
	} else {
		r0 = ret.Get(0).(scanstage.ScanStage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectId, scanId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetScanStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScanStage'
type MockAI_GetScanStage_Call struct {
	*mock.Call
}

// GetScanStage is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId uuid.UUID
//   - scanId uuid.UUID
func (_e *MockAI_Expecter) GetScanStage(ctx interface{}, projectId interface{}, scanId interface{}) *MockAI_GetScanStage_Call {
	return &MockAI_GetScanStage_Call{Call: _e.mock.On("GetScanStage", ctx, projectId, scanId)}
}

func (_c *MockAI_GetScanStage_Call) Run(run func(ctx context.Context, projectId uuid.UUID, scanId uuid.UUID)) *MockAI_GetScanStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAI_GetScanStage_Call) Return(scanStage scanstage.ScanStage, err error) *MockAI_GetScanStage_Call {
	_c.Call.Return(scanStage, err)
	return _c
}

func (_c *MockAI_GetScanStage_Call) RunAndReturn(run func(ctx context.Context, projectId uuid.UUID, scanId uuid.UUID) (scanstage.ScanStage, error)) *MockAI_GetScanStage_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeWithRetry provides a mock function for the type MockAI
func (_mock *MockAI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type MockAI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) InitializeWithRetry(ctx interface{}) *MockAI_InitializeWithRetry_Call {
	return &MockAI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *MockAI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *MockAI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) Return(err error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// WatchScanStage provides a mock function for the type MockAI
func (_mock *MockAI) WatchScanStage(ctx context.Context, scanId uuid.UUID) (<-chan scanstage.ScanStage, error) {
	ret := _mock.Called(ctx, scanId)

	if len(ret) == 0 {
		panic("no return value specified for WatchScanStage")
	}

	var r0 <-chan scanstage.ScanStage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (<-chan scanstage.ScanStage, error)); ok {
		return returnFunc(ctx, scanId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) <-chan scanstage.ScanStage); ok {
		r0 = returnFunc(ctx, scanId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan scanstage.ScanStage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, scanId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_WatchScanStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchScanStage'
type MockAI_WatchScanStage_Call struct {
	*mock.Call
}

// WatchScanStage is a helper method to define mock.On call
//   - ctx context.Context
//   - scanId uuid.UUID
func (_e *MockAI_Expecter) WatchScanStage(ctx interface{}, scanId interface{}) *MockAI_WatchScanStage_Call {
	return &MockAI_WatchScanStage_Call{Call: _e.mock.On("WatchScanStage", ctx, scanId)}
}

func (_c *MockAI_WatchScanStage_Call) Run(run func(ctx context.Context, scanId uuid.UUID)) *MockAI_WatchScanStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAI_WatchScanStage_Call) Return(scanStageCh <-chan scanstage.ScanStage, err error) *MockAI_WatchScanStage_Call {
	_c.Call.Return(scanStageCh, err)
	return _c
}

func (_c *MockAI_WatchScanStage_Call) RunAndReturn(run func(ctx context.Context, scanId uuid.UUID) (<-chan scanstage.ScanStage, error)) *MockAI_WatchScanStage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLI creates a new instance of MockCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLI {
	mock := &MockCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLI is an autogenerated mock type for the CLI type
type MockCLI struct {
	mock.Mock
}

type MockCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLI) EXPECT() *MockCLI_Expecter {
	return &MockCLI_Expecter{mock: &_m.Mock}
}

// ReturnText provides a mock function for the type MockCLI
func (_mock *MockCLI) ReturnText(ctx context.Context, text string) {
	_mock.Called(ctx, text)
	return
}

// MockCLI_ReturnText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnText'
type MockCLI_ReturnText_Call struct {
	*mock.Call
}

// ReturnText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockCLI_Expecter) ReturnText(ctx interface{}, text interface{}) *MockCLI_ReturnText_Call {
	return &MockCLI_ReturnText_Call{Call: _e.mock.On("ReturnText", ctx, text)}
}

func (_c *MockCLI_ReturnText_Call) Run(run func(ctx context.Context, text string)) *MockCLI_ReturnText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_ReturnText_Call) Return() *MockCLI_ReturnText_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ReturnText_Call) RunAndReturn(run func(ctx context.Context, text string)) *MockCLI_ReturnText_Call {
	_c.Run(run)
	return _c
}

// ShowText provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowText(ctx context.Context, text string) {
	_mock.Called(ctx, text)
	return
}

// MockCLI_ShowText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowText'
type MockCLI_ShowText_Call struct {
	*mock.Call
}

// ShowText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockCLI_Expecter) ShowText(ctx interface{}, text interface{}) *MockCLI_ShowText_Call {
	return &MockCLI_ShowText_Call{Call: _e.mock.On("ShowText", ctx, text)}
}

func (_c *MockCLI_ShowText_Call) Run(run func(ctx context.Context, text string)) *MockCLI_ShowText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_ShowText_Call) Return() *MockCLI_ShowText_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowText_Call) RunAndReturn(run func(ctx context.Context, text string)) *MockCLI_ShowText_Call {
	_c.Run(run)
	return _c
}

// ShowTextf provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowTextf(ctx context.Context, format string, a ...any) {
	if len(a) > 0 {
		_mock.Called(ctx, format, a)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockCLI_ShowTextf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowTextf'
type MockCLI_ShowTextf_Call struct {
	*mock.Call
}

// ShowTextf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - a ...any
func (_e *MockCLI_Expecter) ShowTextf(ctx interface{}, format interface{}, a ...interface{}) *MockCLI_ShowTextf_Call {
	return &MockCLI_ShowTextf_Call{Call: _e.mock.On("ShowTextf",
		append([]interface{}{ctx, format}, a...)...)}
}

func (_c *MockCLI_ShowTextf_Call) Run(run func(ctx context.Context, format string, a ...any)) *MockCLI_ShowTextf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCLI_ShowTextf_Call) Return() *MockCLI_ShowTextf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowTextf_Call) RunAndReturn(run func(ctx context.Context, format string, a ...any)) *MockCLI_ShowTextf_Call {
	_c.Run(run)
	return _c
}
