// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAI creates a new instance of AI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AI {
	mock := &AI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AI is an autogenerated mock type for the AI type
type AI struct {
	mock.Mock
}

type AI_Expecter struct {
	mock *mock.Mock
}

func (_m *AI) EXPECT() *AI_Expecter {
	return &AI_Expecter{mock: &_m.Mock}
}

// GetReport provides a mock function for the type AI
func (_mock *AI) GetReport(ctx context.Context, projectId uuid.UUID, scanResultId uuid.UUID, templateId uuid.UUID, includeComments bool, includeDFD bool, includeGlossary bool) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary)

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, bool, bool, bool) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, bool, bool, bool) io.ReadCloser); ok {
		r0 = returnFunc(ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, bool, bool, bool) error); ok {
		r1 = returnFunc(ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AI_GetReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReport'
type AI_GetReport_Call struct {
	*mock.Call
}

// GetReport is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId uuid.UUID
//   - scanResultId uuid.UUID
//   - templateId uuid.UUID
//   - includeComments bool
//   - includeDFD bool
//   - includeGlossary bool
func (_e *AI_Expecter) GetReport(ctx interface{}, projectId interface{}, scanResultId interface{}, templateId interface{}, includeComments interface{}, includeDFD interface{}, includeGlossary interface{}) *AI_GetReport_Call {
	return &AI_GetReport_Call{Call: _e.mock.On("GetReport", ctx, projectId, scanResultId, templateId, includeComments, includeDFD, includeGlossary)}
}

func (_c *AI_GetReport_Call) Run(run func(ctx context.Context, projectId uuid.UUID, scanResultId uuid.UUID, templateId uuid.UUID, includeComments bool, includeDFD bool, includeGlossary bool)) *AI_GetReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *AI_GetReport_Call) Return(readCloser io.ReadCloser, err error) *AI_GetReport_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *AI_GetReport_Call) RunAndReturn(run func(ctx context.Context, projectId uuid.UUID, scanResultId uuid.UUID, templateId uuid.UUID, includeComments bool, includeDFD bool, includeGlossary bool) (io.ReadCloser, error)) *AI_GetReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplateId provides a mock function for the type AI
func (_mock *AI) GetTemplateId(ctx context.Context, reportType string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, reportType)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateId")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, reportType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, reportType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, reportType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AI_GetTemplateId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateId'
type AI_GetTemplateId_Call struct {
	*mock.Call
}

// GetTemplateId is a helper method to define mock.On call
//   - ctx context.Context
//   - reportType string
func (_e *AI_Expecter) GetTemplateId(ctx interface{}, reportType interface{}) *AI_GetTemplateId_Call {
	return &AI_GetTemplateId_Call{Call: _e.mock.On("GetTemplateId", ctx, reportType)}
}

func (_c *AI_GetTemplateId_Call) Run(run func(ctx context.Context, reportType string)) *AI_GetTemplateId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AI_GetTemplateId_Call) Return(uUID uuid.UUID, err error) *AI_GetTemplateId_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *AI_GetTemplateId_Call) RunAndReturn(run func(ctx context.Context, reportType string) (uuid.UUID, error)) *AI_GetTemplateId_Call {
	_c.Call.Return(run)
	return _c
}
