// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewCLI creates a new instance of CLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CLI {
	mock := &CLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CLI is an autogenerated mock type for the CLI type
type CLI struct {
	mock.Mock
}

type CLI_Expecter struct {
	mock *mock.Mock
}

func (_m *CLI) EXPECT() *CLI_Expecter {
	return &CLI_Expecter{mock: &_m.Mock}
}

// ShowReader provides a mock function for the type CLI
func (_mock *CLI) ShowReader(r io.Reader) error {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ShowReader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CLI_ShowReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowReader'
type CLI_ShowReader_Call struct {
	*mock.Call
}

// ShowReader is a helper method to define mock.On call
//   - r io.Reader
func (_e *CLI_Expecter) ShowReader(r interface{}) *CLI_ShowReader_Call {
	return &CLI_ShowReader_Call{Call: _e.mock.On("ShowReader", r)}
}

func (_c *CLI_ShowReader_Call) Run(run func(r io.Reader)) *CLI_ShowReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CLI_ShowReader_Call) Return(err error) *CLI_ShowReader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CLI_ShowReader_Call) RunAndReturn(run func(r io.Reader) error) *CLI_ShowReader_Call {
	_c.Call.Return(run)
	return _c
}

// ShowText provides a mock function for the type CLI
func (_mock *CLI) ShowText(text string) {
	_mock.Called(text)
	return
}

// CLI_ShowText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowText'
type CLI_ShowText_Call struct {
	*mock.Call
}

// ShowText is a helper method to define mock.On call
//   - text string
func (_e *CLI_Expecter) ShowText(text interface{}) *CLI_ShowText_Call {
	return &CLI_ShowText_Call{Call: _e.mock.On("ShowText", text)}
}

func (_c *CLI_ShowText_Call) Run(run func(text string)) *CLI_ShowText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CLI_ShowText_Call) Return() *CLI_ShowText_Call {
	_c.Call.Return()
	return _c
}

func (_c *CLI_ShowText_Call) RunAndReturn(run func(text string)) *CLI_ShowText_Call {
	_c.Run(run)
	return _c
}

// ShowTextf provides a mock function for the type CLI
func (_mock *CLI) ShowTextf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// CLI_ShowTextf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowTextf'
type CLI_ShowTextf_Call struct {
	*mock.Call
}

// ShowTextf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *CLI_Expecter) ShowTextf(format interface{}, args ...interface{}) *CLI_ShowTextf_Call {
	return &CLI_ShowTextf_Call{Call: _e.mock.On("ShowTextf",
		append([]interface{}{format}, args...)...)}
}

func (_c *CLI_ShowTextf_Call) Run(run func(format string, args ...any)) *CLI_ShowTextf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *CLI_ShowTextf_Call) Return() *CLI_ShowTextf_Call {
	_c.Call.Return()
	return _c
}

func (_c *CLI_ShowTextf_Call) RunAndReturn(run func(format string, args ...any)) *CLI_ShowTextf_Call {
	_c.Run(run)
	return _c
}
