// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rollback

import (
	"context"

	"github.com/POSIdev-community/aictl/internal/core/domain/scafeeds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAI creates a new instance of MockAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAI {
	mock := &MockAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAI is an autogenerated mock type for the AI type
type MockAI struct {
	mock.Mock
}

type MockAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAI) EXPECT() *MockAI_Expecter {
	return &MockAI_Expecter{mock: &_m.Mock}
}

// InitializeWithRetry provides a mock function for the type MockAI
func (_mock *MockAI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type MockAI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) InitializeWithRetry(ctx interface{}) *MockAI_InitializeWithRetry_Call {
	return &MockAI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *MockAI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *MockAI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) Return(err error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackScaFeeds provides a mock function for the type MockAI
func (_mock *MockAI) RollbackScaFeeds(ctx context.Context) (scafeeds.Package, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackScaFeeds")
	}

	var r0 scafeeds.Package
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (scafeeds.Package, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) scafeeds.Package); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(scafeeds.Package)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_RollbackScaFeeds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackScaFeeds'
type MockAI_RollbackScaFeeds_Call struct {
	*mock.Call
}

// RollbackScaFeeds is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) RollbackScaFeeds(ctx interface{}) *MockAI_RollbackScaFeeds_Call {
	return &MockAI_RollbackScaFeeds_Call{Call: _e.mock.On("RollbackScaFeeds", ctx)}
}

func (_c *MockAI_RollbackScaFeeds_Call) Run(run func(ctx context.Context)) *MockAI_RollbackScaFeeds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_RollbackScaFeeds_Call) Return(packageParam scafeeds.Package, err error) *MockAI_RollbackScaFeeds_Call {
	_c.Call.Return(packageParam, err)
	return _c
}

func (_c *MockAI_RollbackScaFeeds_Call) RunAndReturn(run func(ctx context.Context) (scafeeds.Package, error)) *MockAI_RollbackScaFeeds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLI creates a new instance of MockCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLI {
	mock := &MockCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLI is an autogenerated mock type for the CLI type
type MockCLI struct {
	mock.Mock
}

type MockCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLI) EXPECT() *MockCLI_Expecter {
	return &MockCLI_Expecter{mock: &_m.Mock}
}

// AskConfirmation provides a mock function for the type MockCLI
func (_mock *MockCLI) AskConfirmation(ctx context.Context, question string) (bool, error) {
	ret := _mock.Called(ctx, question)

	if len(ret) == 0 {
		panic("no return value specified for AskConfirmation")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, question)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, question)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, question)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCLI_AskConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AskConfirmation'
type MockCLI_AskConfirmation_Call struct {
	*mock.Call
}

// AskConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - question string
func (_e *MockCLI_Expecter) AskConfirmation(ctx interface{}, question interface{}) *MockCLI_AskConfirmation_Call {
	return &MockCLI_AskConfirmation_Call{Call: _e.mock.On("AskConfirmation", ctx, question)}
}

func (_c *MockCLI_AskConfirmation_Call) Run(run func(ctx context.Context, question string)) *MockCLI_AskConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_AskConfirmation_Call) Return(b bool, err error) *MockCLI_AskConfirmation_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCLI_AskConfirmation_Call) RunAndReturn(run func(ctx context.Context, question string) (bool, error)) *MockCLI_AskConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// ReturnText provides a mock function for the type MockCLI
func (_mock *MockCLI) ReturnText(ctx context.Context, text string) {
	_mock.Called(ctx, text)
	return
}

// MockCLI_ReturnText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnText'
type MockCLI_ReturnText_Call struct {
	*mock.Call
}

// ReturnText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockCLI_Expecter) ReturnText(ctx interface{}, text interface{}) *MockCLI_ReturnText_Call {
	return &MockCLI_ReturnText_Call{Call: _e.mock.On("ReturnText", ctx, text)}
}

func (_c *MockCLI_ReturnText_Call) Run(run func(ctx context.Context, text string)) *MockCLI_ReturnText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_ReturnText_Call) Return() *MockCLI_ReturnText_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ReturnText_Call) RunAndReturn(run func(ctx context.Context, text string)) *MockCLI_ReturnText_Call {
	_c.Run(run)
	return _c
}

// ShowText provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowText(ctx context.Context, text string) {
	_mock.Called(ctx, text)
	return
}

// MockCLI_ShowText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowText'
type MockCLI_ShowText_Call struct {
	*mock.Call
}

// ShowText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockCLI_Expecter) ShowText(ctx interface{}, text interface{}) *MockCLI_ShowText_Call {
	return &MockCLI_ShowText_Call{Call: _e.mock.On("ShowText", ctx, text)}
}

func (_c *MockCLI_ShowText_Call) Run(run func(ctx context.Context, text string)) *MockCLI_ShowText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_ShowText_Call) Return() *MockCLI_ShowText_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowText_Call) RunAndReturn(run func(ctx context.Context, text string)) *MockCLI_ShowText_Call {
	_c.Run(run)
	return _c
}

// ShowTextf provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowTextf(ctx context.Context, format string, a ...any) {
	if len(a) > 0 {
		_mock.Called(ctx, format, a)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockCLI_ShowTextf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowTextf'
type MockCLI_ShowTextf_Call struct {
	*mock.Call
}

// ShowTextf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - a ...any
func (_e *MockCLI_Expecter) ShowTextf(ctx interface{}, format interface{}, a ...interface{}) *MockCLI_ShowTextf_Call {
	return &MockCLI_ShowTextf_Call{Call: _e.mock.On("ShowTextf",
		append([]interface{}{ctx, format}, a...)...)}
}

func (_c *MockCLI_ShowTextf_Call) Run(run func(ctx context.Context, format string, a ...any)) *MockCLI_ShowTextf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCLI_ShowTextf_Call) Return() *MockCLI_ShowTextf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowTextf_Call) RunAndReturn(run func(ctx context.Context, format string, a ...any)) *MockCLI_ShowTextf_Call {
	_c.Run(run)
	return _c
}
