// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package scafeeds

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAI creates a new instance of MockAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAI {
	mock := &MockAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAI is an autogenerated mock type for the AI type
type MockAI struct {
	mock.Mock
}

type MockAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAI) EXPECT() *MockAI_Expecter {
	return &MockAI_Expecter{mock: &_m.Mock}
}

// InitializeWithRetry provides a mock function for the type MockAI
func (_mock *MockAI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type MockAI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) InitializeWithRetry(ctx interface{}) *MockAI_InitializeWithRetry_Call {
	return &MockAI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *MockAI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *MockAI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) Return(err error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateScaFeeds provides a mock function for the type MockAI
func (_mock *MockAI) UpdateScaFeeds(ctx context.Context, path string, version string) error {
	ret := _mock.Called(ctx, path, version)

	if len(ret) == 0 {
		panic("no return value specified for UpdateScaFeeds")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, path, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_UpdateScaFeeds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateScaFeeds'
type MockAI_UpdateScaFeeds_Call struct {
	*mock.Call
}

// UpdateScaFeeds is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - version string
func (_e *MockAI_Expecter) UpdateScaFeeds(ctx interface{}, path interface{}, version interface{}) *MockAI_UpdateScaFeeds_Call {
	return &MockAI_UpdateScaFeeds_Call{Call: _e.mock.On("UpdateScaFeeds", ctx, path, version)}
}

func (_c *MockAI_UpdateScaFeeds_Call) Run(run func(ctx context.Context, path string, version string)) *MockAI_UpdateScaFeeds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAI_UpdateScaFeeds_Call) Return(err error) *MockAI_UpdateScaFeeds_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_UpdateScaFeeds_Call) RunAndReturn(run func(ctx context.Context, path string, version string) error) *MockAI_UpdateScaFeeds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLI creates a new instance of MockCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLI {
	mock := &MockCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLI is an autogenerated mock type for the CLI type
type MockCLI struct {
	mock.Mock
}

type MockCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLI) EXPECT() *MockCLI_Expecter {
	return &MockCLI_Expecter{mock: &_m.Mock}
}

// ShowTextf provides a mock function for the type MockCLI
func (_mock *MockCLI) ShowTextf(ctx context.Context, format string, a ...any) {
	if len(a) > 0 {
		_mock.Called(ctx, format, a)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// MockCLI_ShowTextf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowTextf'
type MockCLI_ShowTextf_Call struct {
	*mock.Call
}

// ShowTextf is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - a ...any
func (_e *MockCLI_Expecter) ShowTextf(ctx interface{}, format interface{}, a ...interface{}) *MockCLI_ShowTextf_Call {
	return &MockCLI_ShowTextf_Call{Call: _e.mock.On("ShowTextf",
		append([]interface{}{ctx, format}, a...)...)}
}

func (_c *MockCLI_ShowTextf_Call) Run(run func(ctx context.Context, format string, a ...any)) *MockCLI_ShowTextf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCLI_ShowTextf_Call) Return() *MockCLI_ShowTextf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ShowTextf_Call) RunAndReturn(run func(ctx context.Context, format string, a ...any)) *MockCLI_ShowTextf_Call {
	_c.Run(run)
	return _c
}
