// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package checkpolicies

import (
	"context"

	"github.com/POSIdev-community/aictl/internal/core/domain/policystate"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAI creates a new instance of MockAI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAI {
	mock := &MockAI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAI is an autogenerated mock type for the AI type
type MockAI struct {
	mock.Mock
}

type MockAI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAI) EXPECT() *MockAI_Expecter {
	return &MockAI_Expecter{mock: &_m.Mock}
}

// GetScanPolicyState provides a mock function for the type MockAI
func (_mock *MockAI) GetScanPolicyState(ctx context.Context, projectId uuid.UUID, scanId uuid.UUID) (policystate.State, error) {
	ret := _mock.Called(ctx, projectId, scanId)

	if len(ret) == 0 {
		panic("no return value specified for GetScanPolicyState")
	}

	var r0 policystate.State
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (policystate.State, error)); ok {
		return returnFunc(ctx, projectId, scanId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) policystate.State); ok {
		r0 = returnFunc(ctx, projectId, scanId)
	} else {
		r0 = ret.Get(0).(policystate.State)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectId, scanId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAI_GetScanPolicyState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScanPolicyState'
type MockAI_GetScanPolicyState_Call struct {
	*mock.Call
}

// GetScanPolicyState is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId uuid.UUID
//   - scanId uuid.UUID
func (_e *MockAI_Expecter) GetScanPolicyState(ctx interface{}, projectId interface{}, scanId interface{}) *MockAI_GetScanPolicyState_Call {
	return &MockAI_GetScanPolicyState_Call{Call: _e.mock.On("GetScanPolicyState", ctx, projectId, scanId)}
}

func (_c *MockAI_GetScanPolicyState_Call) Run(run func(ctx context.Context, projectId uuid.UUID, scanId uuid.UUID)) *MockAI_GetScanPolicyState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAI_GetScanPolicyState_Call) Return(state policystate.State, err error) *MockAI_GetScanPolicyState_Call {
	_c.Call.Return(state, err)
	return _c
}

func (_c *MockAI_GetScanPolicyState_Call) RunAndReturn(run func(ctx context.Context, projectId uuid.UUID, scanId uuid.UUID) (policystate.State, error)) *MockAI_GetScanPolicyState_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeWithRetry provides a mock function for the type MockAI
func (_mock *MockAI) InitializeWithRetry(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitializeWithRetry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAI_InitializeWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeWithRetry'
type MockAI_InitializeWithRetry_Call struct {
	*mock.Call
}

// InitializeWithRetry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAI_Expecter) InitializeWithRetry(ctx interface{}) *MockAI_InitializeWithRetry_Call {
	return &MockAI_InitializeWithRetry_Call{Call: _e.mock.On("InitializeWithRetry", ctx)}
}

func (_c *MockAI_InitializeWithRetry_Call) Run(run func(ctx context.Context)) *MockAI_InitializeWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) Return(err error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAI_InitializeWithRetry_Call) RunAndReturn(run func(ctx context.Context) error) *MockAI_InitializeWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCLI creates a new instance of MockCLI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLI {
	mock := &MockCLI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLI is an autogenerated mock type for the CLI type
type MockCLI struct {
	mock.Mock
}

type MockCLI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLI) EXPECT() *MockCLI_Expecter {
	return &MockCLI_Expecter{mock: &_m.Mock}
}

// ReturnText provides a mock function for the type MockCLI
func (_mock *MockCLI) ReturnText(ctx context.Context, text string) {
	_mock.Called(ctx, text)
	return
}

// MockCLI_ReturnText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnText'
type MockCLI_ReturnText_Call struct {
	*mock.Call
}

// ReturnText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockCLI_Expecter) ReturnText(ctx interface{}, text interface{}) *MockCLI_ReturnText_Call {
	return &MockCLI_ReturnText_Call{Call: _e.mock.On("ReturnText", ctx, text)}
}

func (_c *MockCLI_ReturnText_Call) Run(run func(ctx context.Context, text string)) *MockCLI_ReturnText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCLI_ReturnText_Call) Return() *MockCLI_ReturnText_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCLI_ReturnText_Call) RunAndReturn(run func(ctx context.Context, text string)) *MockCLI_ReturnText_Call {
	_c.Run(run)
	return _c
}
